import Head from "next/head";
import Image from "next/image";
import logo from '../public/assets/logo1.png'



export default function AboutUs () {
    return (
        <>

        <Head>
        <title>The Recipe Room</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/logo1.png" />
        </Head>

        
        <div className="description">
            <h1 className="abouttitle">About Us</h1>

            <div className="descriptionp">
                <p>Welcome to The Recipe Room - Where Culinary Creations Come to Life!</p>
            </div>

            <br />

            <div className="mobile">
            <div className="showOnMobile">
                <Image 
                    src={logo}
                    alt="The Recipe Room Logo"
                    width=''
                    height=''
                />
            </div>
            </div>

            <div className="descriptionp1">
                <p>At The Recipe Room, we believe in the power of good food to bring people together. Our passion for cooking and sharing delightful recipes inspired us to create this culinary haven.</p>
            </div>
            <br />
            <br />

            <div className="descriptionp1">
                <p>Whether you're a seasoned chef or a kitchen novice, our platform is designed to cater to your culinary needs and aspirations.</p>

            </div>
        </div>

    

        
        </>
    );
}

