import Image from "next/image";
import fs from "fs";
import path from "path";
import Head from "next/head";
import { useState } from "react";
import Link from "next/link";

export default function Recipe({ recipe }) {
  const [selectedCategory, setSelectedCategory] = useState(null);
  const [searchTerm, setSearchTerm] = useState("");
  const handleCategoryClick = (category) => {
    setSelectedCategory(category);
  };

  const handleSearch = (event) => {
    setSearchTerm(event.target.value);
  };

  let filteredRecipe = recipe;
  if (selectedCategory) {
    filteredRecipe = recipe.filter((r) => r.Category === selectedCategory);
  }

  const filteredSearchRecipe = filteredRecipe.filter(
    (recipe) =>
      recipe &&
      recipe.Recipe_Name &&
      typeof recipe.Recipe_Name === "string" &&
      recipe.Recipe_Name.toLowerCase().includes(searchTerm.toLowerCase())
  );
  return (
    <>
      <Head>
        <title>The Recipe Room</title>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
          integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer"
        />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="assets/logo1.png" />
      </Head>

      <div className="container"> 
      <input className="searchbar" placeholder="Search Recipes..." onKeyUp={handleSearch}></input>
      <div className="search"></div>
      </div>
      <section className="button_flexing">
        <button
          onClick={() => handleCategoryClick(null)}
          className="recipebtn"
        >
          All
        </button>
        <button
          onClick={() => handleCategoryClick("Breakfast")}
          className="recipebtn"
        >
          Breakfast
        </button>
        <button
          onClick={() => handleCategoryClick("Lunch")}
          className="recipebtn"
        >
          Lunch
        </button>
        <button
          onClick={() => handleCategoryClick("Salad")}
          className="recipebtn"
        >
          Salad
        </button>
        <button
          onClick={() => handleCategoryClick("Dinner")}
          className="recipebtn"
        >
          Dinner
        </button>
      </section>

      <section className="recipesection">
        {filteredSearchRecipe.map((recipe) => {
          return (
            <Link
              className="recipeboxes"
              href={`/view/${recipe.id}`}
              key={recipe.id}
            >
              <Image
                src={`/recipics/${recipe.image1}`}
                alt=""
                width="200"
                height="100"
              />
              <h5 className="recipe-titles">{recipe.Recipe_Name}</h5>
            </Link>
          );
        })}
      </section>
    </>
  );
}

export async function getStaticProps() {
  const filePath = path.join(process.cwd(), "./pages/recipe.json");
  const fileContent = fs.readFileSync(filePath, "utf8");
  const data = JSON.parse(fileContent);

  console.log(data);
  return {
    props: {
      recipe: data,
    },
  };
}